name: build

on:
  push:
  workflow_dispatch:

jobs:
  build-pc:
    name: build-pc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependency
        run: sudo apt-get install mingw-w64

      - name: Build
        run: |
          make linux
          make windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: table-pc
          path: out/

  build-android:
    name: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependency
        run: |
          LATEST_NDK_URL=$(curl -s https://developer.android.com/ndk/downloads | grep -oP 'https://dl.google.com/android/repository/android-ndk-r[0-9]+[a-z]?-linux\.zip' | head -n 1)
          [ -z "$LATEST_NDK_URL" ] && LATEST_NDK_URL="https://dl.google.com/android/repository/android-ndk-r27c-linux.zip"
          wget "$LATEST_NDK_URL" -O android-ndk.zip
          TEMP_DIR=$(mktemp -d)
          unzip android-ndk.zip -d "$TEMP_DIR"
          EXTRACTED_DIR=$(find "$TEMP_DIR" -maxdepth 1 -name "android-ndk-*" -type d | head -n 1)
          mv -f "$EXTRACTED_DIR" "$(pwd)/android-ndk"

      - name: Build
        run: |
          export PATH="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
          make android

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: table-android
          path: out/
